name = "Create: Friends & Family - To the Sky"
author = "CyanCupcake"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a1024a9f340583d2596738b63b7f84d711b55aa1b59b5d2777e80c6cace0753"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
