name = "Create: Friends & Family - To the Sky"
author = "CyanCupcake"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab36630bfc80a784d45878f48024ad0e68127c5cbcd28bb80580e8d2cf28074c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
