#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 17 12:41:05 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryReimagined_r5.7.1.zip
